from __future__ import annotations

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from api.config import settings

_PLAIN = """\
Your MCP Server "{name}" is ready!

Download:
  {url}

⚠️  This link expires in {hours} hours.

How to run
----------
  unzip mcp-server.zip
  cd {name}
  uv venv .venv
  uv pip install --python .venv/bin/python -r requirements.txt
  .venv/bin/python main.py

The server starts in STDIO mode by default — compatible with Claude Desktop,
Cursor, and MCP Inspector.

— MCP Forge
"""

_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:system-ui,-apple-system,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 0;">
  <tr><td align="center">
    <table width="560" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;border:1px solid #e2e8f0;overflow:hidden;">
      <!-- Header -->
      <tr><td style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:32px;text-align:center;">
        <h1 style="margin:0;color:#fff;font-size:24px;font-weight:700;">MCP Forge</h1>
        <p style="margin:8px 0 0;color:#c7d2fe;font-size:14px;">OpenAPI → MCP Server Generator</p>
      </td></tr>
      <!-- Body -->
      <tr><td style="padding:40px;">
        <h2 style="margin:0 0 8px;color:#0f172a;font-size:20px;">Your server is ready 🚀</h2>
        <p style="margin:0 0 24px;color:#475569;">
          <strong>{name}</strong> has been generated and packaged as a ZIP.
        </p>
        <div style="text-align:center;margin:32px 0;">
          <a href="{url}" style="display:inline-block;background:#6366f1;color:#fff;text-decoration:none;
            padding:14px 32px;border-radius:8px;font-weight:600;font-size:16px;">
            Download MCP Server
          </a>
        </div>
        <p style="margin:0 0 24px;color:#ef4444;font-size:13px;text-align:center;">
          ⏳ Link expires in <strong>{hours} hours</strong>
        </p>
        <hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0;">
        <h3 style="margin:0 0 12px;color:#0f172a;font-size:14px;text-transform:uppercase;letter-spacing:.05em;">
          How to run
        </h3>
        <pre style="margin:0;background:#f1f5f9;border-radius:8px;padding:16px;font-size:13px;
          color:#334155;overflow:auto;line-height:1.6;">unzip mcp-server.zip
cd {name}
uv venv .venv
uv pip install --python .venv/bin/python -r requirements.txt
.venv/bin/python main.py</pre>
        <p style="margin:16px 0 0;color:#64748b;font-size:13px;">
          Starts in <strong>STDIO</strong> mode — works with Claude Desktop, Cursor, and MCP Inspector.
        </p>
      </td></tr>
      <!-- Footer -->
      <tr><td style="background:#f8fafc;padding:20px;text-align:center;border-top:1px solid #e2e8f0;">
        <p style="margin:0;color:#94a3b8;font-size:12px;">Generated by MCP Forge</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>
"""


async def send_download_email(to_email: str, download_url: str, server_name: str) -> None:
    hours = settings.TOKEN_EXPIRY_HOURS

    if not settings.SMTP_HOST or not settings.SMTP_USERNAME:
        # Dev mode: print to console
        print(f"\n[EMAIL] To: {to_email}")
        print(f"[EMAIL] Server: {server_name}")
        print(f"[EMAIL] Download: {download_url}\n")
        return

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Your MCP Server is ready 🚀"
    msg["From"] = f"{settings.EMAIL_FROM_NAME} <{settings.EMAIL_FROM}>"
    msg["To"] = to_email

    msg.attach(MIMEText(_PLAIN.format(name=server_name, url=download_url, hours=hours), "plain"))
    msg.attach(MIMEText(_HTML.format(name=server_name, url=download_url, hours=hours), "html"))

    with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
        if settings.SMTP_USE_TLS:
            server.starttls()
        server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
        server.send_message(msg)
